SEED: 42
DEVICE: [0]
# DATASET
ROOT: ./data/train_images/
DATA_TRAIN: ./data/train.csv
NUM_WORKERS: 8
MODE: non-cls


# training
TRAIN_DATASET:
 PY: datasets.dataset
 CLASS: SteelDataset
 ARGS:
  root_dataset: ./data/train_images/
  list_data: ./data/train.csv
  phase: train
  mode: non-cls

VALID_DATASET:
 PY: datasets.dataset
 CLASS: SteelDataset
 ARGS:
  root_dataset: ./data/train_images/
  list_data: ./data/train.csv
  phase: valid
  mode: non-cls
TRAIN_DATALOADER:
 PY: torch.utils.data
 CLASS: DataLoader
 ARGS:
  batch_size: 2
  shuffle: True
  num_workers: 8
  pin_memory: True

VALID_DATALOADER:
 PY: torch.utils.data
 CLASS: DataLoader
 ARGS:
  batch_size: 2
  shuffle: False
  num_workers: 8
  pin_memory: True

MODEL:
 PY: modules.segmentation_models.fpn.model
 CLASS: FPN
 ARGS:
  classes: 4
  encoder_name: se_resnext50_32x4d
  activation: softmax
  encoder_weights: imagenet


CRITERION:
 PY: models.losses
 CLASS: ComboLoss
 ARGS:
  weights:
   bce: 1
   dice: 1
   focal: 1

OPTIMIZER:
 PY: torch.optim
 CLASS: Adam
 ARGS:
  lr: 0.0001
  weight_decay: 0.000005

SCHEDULER:
 PY: torch.optim.lr_scheduler
 CLASS: ReduceLROnPlateau
 ARGS:
  mode: max
  factor: 0.1
  patience: 2
  threshold: 0.0000001
  min_lr: 0.0000001


GRADIENT_ACCUMULATION_STEPS: 4
GRADIENT_CLIPPING: 0.1
NUM_EPOCH: 200
EARLY_STOPPING: 7
VALIDATION_FREQUENCY: 3
SAVED_PERIOD: 5
CHECKPOINT_DIR: /opt/ml/model/
RESUME_PATH: